version: "3.5"
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
    ipc: host

  test-unit:
    build:
      context: .
      target: builder
    image: ggw-test-image 
    command: npm run test
