export const metaMock = {
  _embedded: {
    indicatoren_definities: [
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17/?_format=json",
            title: "BEV0_17",
            variabele: "BEV0_17",
          },
        },
        sort: 1090,
        variabele: "BEV0_17",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking leeftijd",
        label: "0-17 jaar",
        labelKort: "0-17 jaar",
        definitie:
          "Personen in de leeftijd 0 t/m 17 jaar die op de peildatum zijn geregistreerd in de gemeente Amsterdam. De leeftijd is het aantal gehele jaren dat op de dag voorafgaand aan de peildatum is verstreken sinds de geboortedatum van de persoon.",
        bron: "Basisinformatie / OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "1 keer per jaar",
        rekeneenheid: 2,
        symbool: null,
        groep: null,
        format: "F8.",
        berekendeVariabelen: "1",
        themaKerncijfertabel: null,
        tussenkopjeKerncijfertabel: null,
        kleurenpalet: 9,
        legendaCode: 3,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population age",
        label1: "0 - 17 years",
        definition: "Number of people registered in Amsterdam aged 0 to 17 on January 1st.",
        referenceDate: "1 January ",
        frequency: "once a year",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        sort: 1100,
        variabele: "BEV0_17_P",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking leeftijd",
        label: "0-17 jaar (%)",
        labelKort: "0-17 jaar (%)",
        definitie: "Het aandeel van de bevolking met een leeftijd van 0 t/m 17 jaar",
        bron: "Basisinformatie / OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "1 keer per jaar",
        rekeneenheid: 1,
        symbool: "%",
        groep: null,
        format: "F5.1",
        berekendeVariabelen: "1",
        themaKerncijfertabel: "Bevolking",
        tussenkopjeKerncijfertabel: "Personen",
        kleurenpalet: 3,
        legendaCode: 2,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population age",
        label1: "0 - 17 years (%)",
        definition: "Percentage of the population aged 0 to 17 on January 1st.",
        referenceDate: "1 January ",
        frequency: "once a year",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_PROG/?_format=json",
            title: "BEV0_17_PROG",
            variabele: "BEV0_17_PROG",
          },
        },
        sort: 30,
        variabele: "BEV0_17_PROG",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking",
        label: "Bevolkingsprognose  (0-17)",
        labelKort: "Bevolkingsprognose (0-17)",
        definitie:
          "Prognose uit 2021 voor het aantal 0 tot en met 17-jarigen op 1 januari . Het inwonertal in toekomstige jaren wordt berekend aan de hand van verwachte demografische trends, in combinatie met de verwachte omvang van de woningvoorraad.",
        bron: "OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "eenmalig",
        rekeneenheid: 2,
        symbool: null,
        groep: null,
        format: "F8.",
        berekendeVariabelen: null,
        themaKerncijfertabel: null,
        tussenkopjeKerncijfertabel: null,
        kleurenpalet: 9,
        legendaCode: 3,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population",
        label1: "Population projection 2021  (0-17 years)",
        definition: "Projection in 2021 for the population size aged 0 to 17 on January 1st in future years.",
        referenceDate: "1 January ",
        frequency: "one-off",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_18/?_format=json",
            title: "BEV0_18",
            variabele: "BEV0_18",
          },
        },
        sort: 1110,
        variabele: "BEV0_18",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking leeftijd",
        label: "0-18 jaar",
        labelKort: "0-18 jaar",
        definitie:
          "Personen in de leeftijd 0 t/m 18 jaar die op de peildatum zijn geregistreerd in de gemeente Amsterdam. De leeftijd is het aantal gehele jaren dat op de dag voorafgaand aan de peildatum is verstreken sinds de geboortedatum van de persoon.",
        bron: "Basisinformatie / OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "1 keer per jaar",
        rekeneenheid: 2,
        symbool: null,
        groep: null,
        format: "F8.",
        berekendeVariabelen: null,
        themaKerncijfertabel: null,
        tussenkopjeKerncijfertabel: null,
        kleurenpalet: 9,
        legendaCode: 3,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population age",
        label1: "0 - 18 years",
        definition: "Number of people registered in Amsterdam aged 0 to 18 on January 1st.",
        referenceDate: "1 January ",
        frequency: "once a year",
      },
    ],
  },
};
