export const metaMock = {
  _embedded: {
    indicatoren_definities: [
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17/?_format=json",
            title: "BEV0_17",
            variabele: "BEV0_17",
          },
        },
        sort: 1090,
        variabele: "BEV0_17",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking leeftijd",
        label: "0-17 jaar",
        labelKort: "0-17 jaar",
        definitie:
          "Personen in de leeftijd 0 t/m 17 jaar die op de peildatum zijn geregistreerd in de gemeente Amsterdam. De leeftijd is het aantal gehele jaren dat op de dag voorafgaand aan de peildatum is verstreken sinds de geboortedatum van de persoon.",
        bron: "Basisinformatie / OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "1 keer per jaar",
        rekeneenheid: 2,
        symbool: null,
        groep: null,
        format: "F8.",
        berekendeVariabelen: "1",
        themaKerncijfertabel: null,
        tussenkopjeKerncijfertabel: null,
        kleurenpalet: 9,
        legendaCode: 3,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population age",
        label1: "0 - 17 years",
        definition: "Number of people registered in Amsterdam aged 0 to 17 on January 1st.",
        referenceDate: "1 January ",
        frequency: "once a year",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        sort: 1100,
        variabele: "BEV0_17_P",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking leeftijd",
        label: "0-17 jaar (%)",
        labelKort: "0-17 jaar (%)",
        definitie: "Het aandeel van de bevolking met een leeftijd van 0 t/m 17 jaar",
        bron: "Basisinformatie / OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "1 keer per jaar",
        rekeneenheid: 1,
        symbool: "%",
        groep: null,
        format: "F5.1",
        berekendeVariabelen: "1",
        themaKerncijfertabel: "Bevolking",
        tussenkopjeKerncijfertabel: "Personen",
        kleurenpalet: 3,
        legendaCode: 2,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population age",
        label1: "0 - 17 years (%)",
        definition: "Percentage of the population aged 0 to 17 on January 1st.",
        referenceDate: "1 January ",
        frequency: "once a year",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_PROG/?_format=json",
            title: "BEV0_17_PROG",
            variabele: "BEV0_17_PROG",
          },
        },
        sort: 30,
        variabele: "BEV0_17_PROG",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking",
        label: "Bevolkingsprognose  (0-17)",
        labelKort: "Bevolkingsprognose (0-17)",
        definitie:
          "Prognose uit 2021 voor het aantal 0 tot en met 17-jarigen op 1 januari . Het inwonertal in toekomstige jaren wordt berekend aan de hand van verwachte demografische trends, in combinatie met de verwachte omvang van de woningvoorraad.",
        bron: "OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "eenmalig",
        rekeneenheid: 2,
        symbool: null,
        groep: null,
        format: "F8.",
        berekendeVariabelen: null,
        themaKerncijfertabel: null,
        tussenkopjeKerncijfertabel: null,
        kleurenpalet: 9,
        legendaCode: 3,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population",
        label1: "Population projection 2021  (0-17 years)",
        definition: "Projection in 2021 for the population size aged 0 to 17 on January 1st in future years.",
        referenceDate: "1 January ",
        frequency: "one-off",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#indicatorenDefinities",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_18/?_format=json",
            title: "BEV0_18",
            variabele: "BEV0_18",
          },
        },
        sort: 1110,
        variabele: "BEV0_18",
        begrotingsProgramma: "Bevolking",
        thema: "Bevolking leeftijd",
        label: "0-18 jaar",
        labelKort: "0-18 jaar",
        definitie:
          "Personen in de leeftijd 0 t/m 18 jaar die op de peildatum zijn geregistreerd in de gemeente Amsterdam. De leeftijd is het aantal gehele jaren dat op de dag voorafgaand aan de peildatum is verstreken sinds de geboortedatum van de persoon.",
        bron: "Basisinformatie / OIS",
        peildatum: "1  januari",
        verschijningsfrequentie: "1 keer per jaar",
        rekeneenheid: 2,
        symbool: null,
        groep: null,
        format: "F8.",
        berekendeVariabelen: null,
        themaKerncijfertabel: null,
        tussenkopjeKerncijfertabel: null,
        kleurenpalet: 9,
        legendaCode: 3,
        sdMinimumBevTotaal: null,
        sdMinimumWvoorBag: null,
        topicArea: "Population age",
        label1: "0 - 18 years",
        definition: "Number of people registered in Amsterdam aged 0 to 18 on January 1st.",
        referenceDate: "1 January ",
        frequency: "once a year",
      },
    ],
  },
};

export const stdMock = {
  _embedded: {
    statistieken: [
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2005/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2005,
        gemiddelde: 18.9,
        standaardafwijking: 6.183,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2005",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2006/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2006,
        gemiddelde: 18.8,
        standaardafwijking: 6.291,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2006",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2007/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2007,
        gemiddelde: 18.7,
        standaardafwijking: 6.31,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2007",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2008/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2008,
        gemiddelde: 18.5,
        standaardafwijking: 6.315,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2008",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2009/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2009,
        gemiddelde: 18.4,
        standaardafwijking: 6.362,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2009",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2010/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2010,
        gemiddelde: 18.4,
        standaardafwijking: 6.302,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2010",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2011/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2011,
        gemiddelde: 18.3,
        standaardafwijking: 6.137,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2011",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2012/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2012,
        gemiddelde: 18.2,
        standaardafwijking: 6.153,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2012",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2013/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2013,
        gemiddelde: 18.2,
        standaardafwijking: 6.269,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2013",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#statistieken",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/statistieken/BEV0_17_P%7C2014/?_format=json",
            title: "BEV0_17_P",
            indicatorDefinitieId: "BEV0_17_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV0_17_P/?_format=json",
            title: "BEV0_17_P",
            variabele: "BEV0_17_P",
          },
        },
        jaar: 2014,
        gemiddelde: 18.2,
        standaardafwijking: 6.074,
        bron: "sdbc",
        indicatorDefinitieId: "BEV0_17_P",
        id: "BEV0_17_P|2014",
      },
      {
        jaar: 2015,
        gemiddelde: 18.1,
        standaardafwijking: 5.863,
        bron: "sdbc",
        indicatorDefinitieId: "OTHER_VAR",
        id: "BEV0_17_P|2015",
      },
    ],
  },
};

export const kerncijfersMock = {
  _embedded: {
    kerncijfers: [
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2005%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2005,
        gebiedcode15: "A",
        waarde: 10.6,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2005|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2006%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2006,
        gebiedcode15: "A",
        waarde: 10.6,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2006|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2007%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2007,
        gebiedcode15: "A",
        waarde: 10.6,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2007|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2008%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2008,
        gebiedcode15: "A",
        waarde: 10.5,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2008|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2009%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2009,
        gebiedcode15: "A",
        waarde: 10.4,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2009|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2010%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2010,
        gebiedcode15: "A",
        waarde: 10.4,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2010|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2011%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2011,
        gebiedcode15: "A",
        waarde: 10.3,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2011|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2012%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2012,
        gebiedcode15: "A",
        waarde: 10.3,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2012|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2013%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2013,
        gebiedcode15: "A",
        waarde: 10.6,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2013|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2014%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2014,
        gebiedcode15: "A",
        waarde: 10.8,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2014|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2015%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2015,
        gebiedcode15: "A",
        waarde: 11.0,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2015|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2016%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2016,
        gebiedcode15: "A",
        waarde: 11.1,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2016|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2017%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2017,
        gebiedcode15: "A",
        waarde: 11.3,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2017|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2018%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2018,
        gebiedcode15: "A",
        waarde: 11.4,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2018|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2019%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2019,
        gebiedcode15: "A",
        waarde: 11.6,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2019|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2020%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2020,
        gebiedcode15: "A",
        waarde: 11.8,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2020|STAD",
      },
      {
        _links: {
          schema: "https://schemas.data.amsterdam.nl/datasets/bbga/dataset#kerncijfers",
          self: {
            href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/BEV66PLUS_P%7C2021%7CSTAD/?_format=json",
            title: "BEV66PLUS_P",
            indicatorDefinitieId: "BEV66PLUS_P",
          },
          indicatorDefinitie: {
            href: "https://api.data.amsterdam.nl/v1/bbga/indicatoren_definities/BEV66PLUS_P/?_format=json",
            title: "BEV66PLUS_P",
            variabele: "BEV66PLUS_P",
          },
        },
        jaar: 2021,
        gebiedcode15: "A",
        waarde: 12.1,
        indicatorDefinitieId: "BEV66PLUS_P",
        id: "BEV66PLUS_P|2021|STAD",
      },
    ],
  },
  _links: {
    self: {
      href: "https://api.data.amsterdam.nl/v1/bbga/kerncijfers/?indicatorDefinitieId=BEV66PLUS_P&gebiedcode15=STAD&_pageSize=100000&_format=json",
    },
  },
  page: { number: 1, size: 100000 },
};
